### ISSUE TITLE
No CORS headers

### ISSUE THREAD

**Issue by kyv** [apigee-127/swagger-restify#3]
I'm not seeing any CORS headers:

    curl -I 'http://localhost:10010/v1/spec.yaml'

    HTTP/1.1 200 OK
    Content-Type: application/json
    Date: Wed, 17 May 2017 19:14:08 GMT
    Connection: keep-alive

my `swagger_controlers` look like this:

    swagger_controllers:
      - onError: _json_error_handler
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

My api was generated with `swagger project create`. I later updated to latest version of swagger-restify-mw with `npm install swagger-restify-mw@latest --save`.

Am I missing something?

**Comment by revnode** [comment]
@kyv You need to
```
app.use(
      (request, response, next) =>
      {
        response.header('Access-Control-Allow-Origin', '*');
        response.header('Access-Control-Allow-Headers', 'Content-Type, X-Requested-With');
        response.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
        
        return next();
      }
    );
```
in your app.js file.

**Comment by kyv** [comment]
Yea that works.  I thought the cores `swagger_controler` did that for me. I had also tried with `app.use(restify.CORS());`

thanks
